- name: Add SUSFS Configuration Settings
        env:
          DEFCONFIG: arch/arm64/configs/${{ inputs.codename }}_defconfig
        run: |
          in_kernel
          echo "CONFIG_KSU=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_KPROBES_HOOK=n" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$DEFCONFIG"
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$DEFCONFIG"
          echo "CONFIG_TMPFS_XATTR=y" >> "$DEFCONFIG"
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> "$DEFCONFIG"
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> "$DEFCONFIG"
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> "$DEFCONFIG"
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> "$DEFCONFIG"
          echo "CONFIG_TCP_CONG_BBR=y" >> "$DEFCONFIG"
          echo "CONFIG_NET_SCH_FQ=y" >> "$DEFCONFIG"
          echo "CONFIG_TCP_CONG_BIC=n" >> "$DEFCONFIG"
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> "$DEFCONFIG"
          echo "CONFIG_TCP_CONG_HTCP=n" >> "$DEFCONFIG"
          echo "CONFIG_BPF_STREAM_PARSER=y" >> "$DEFCONFIG"
          echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y" >> "$DEFCONFIG"
          echo "CONFIG_NETFILTER_XT_SET=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_MAX=65534" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_BITMAP_IP=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_BITMAP_IPMAC=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_BITMAP_PORT=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_IP=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_IPMARK=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_IPPORT=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_IPPORTIP=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_IPPORTNET=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_IPMAC=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_MAC=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_NETPORTNET=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_NET=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_NETNET=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_NETPORT=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_HASH_NETIFACE=y" >> "$DEFCONFIG"
          echo "CONFIG_IP_SET_LIST_SET=y" >> "$DEFCONFIG"
          echo "CONFIG_IP6_NF_NAT=y" >> "$DEFCONFIG"
          echo "CONFIG_IP6_NF_TARGET_MASQUERADE=y" >> "$DEFCONFIG"
          echo "CONFIG_KPM=n" >> "$DEFCONFIG"
          echo "CONFIG_KSU_MANUAL_SU=n" >> "$DEFCONFIG"
          echo "CONFIG_COMPAT=y" >> "$DEFCONFIG"
          echo "CONFIG_ZRAM_GS_WRITEBACK=y" >> "$DEFCONFIG"
          echo "CONFIG_DEFAULT_BBR=y" >> "$DEFCONFIG"
